### ISSUE TITLE
Support to use multiple DDL-commands in one file

### ISSUE THREAD

**Issue by true-hb** [mickeypearce/oradew-vscode#28]
We often have more than one DDL-commands in file, for example
```
CREATE OR REPLACE PACKAGE xy AS
...
END xy;
/

GRANT EXECUTE ON xy TO PUBLIC
/
```
This ist very useful for us, but it's a problem for ORADEW-extension. 
After compiling I get the message `ERROR PLS-00103: Encountered the symbol "/" `

Isn't it possible to support such a command structure in ORADEW?

**Comment by true-hb** [comment]
For me this _enhancement_ is really necessary. So if it doesn't work, for me it's a **bug**.

I think you might split the file into multiple commands in a safe way by something like this:
`commandList = fileText.split (/\n\/)`

**Comment by mickeypearce** [comment]
Hi, 
have you tried "Run Current File as Script" (F5) command? It executes file with SQL*Plus.
I am adding problem matcher for this command (scripts) and SQLcl as default script runner.
Would that be more useful in your case?

**Comment by mickeypearce** [comment]
Proper script parser is

**Comment by mickeypearce** [comment]
Closed by accident :angry: 

> I think you might split the file into multiple commands in a safe way by something like this:
> `commandList = fileText.split (/\n\/)`

I am avoiding the task of a PL/SQL script parser and waiting for somebody else to write  it... :sweat_smile:

**Comment by true-hb** [comment]
Yes, I think this would be useful. Sounds similar to a build task I use so far according to https://ora-00001.blogspot.com/2017/03/using-vs-code-for-plsql-development.html. This works good for my Packages, but not so good for Triggers:
- when I have a syntax error in the declaration, e.g. `create trigger xx afterx update on` I just get an error message in the console, not in the problem window:
```
 create trigger xx afterx update on
                   *
ERROR at line 1:
ORA-04071: missing BEFORE, AFTER or INSTEAD OF keyword
```
- when I have a problem in the trigger source the error message points to the line number after the `declare` or `begin` of the trigger source, not to the line number in the real source

**Comment by mickeypearce** [comment]
I added `SQLcl` as a default script runner. (It can be changed with "oradew.cliExecutable" setting). 

SQLcl has a better error reporting than SQL*Plus. It also prints correct line offset when running multiple blocks in one script, etc. I think it should correctly match problems also when creating triggers.

**Comment by true-hb** [comment]
I can't get it working for me.

When I use "Compile Current File" I get this
```
> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\node_modules\gulp\bin\gulp.js --cwd d:\git\resus\db --gulpfile c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\out\gulpfile.js --color true --silent true compile --env GBT_TEST --file d:\git\resus\db\src\resus\packages\ABG_MEMTOOLS-body.SQL <

Failure => RESUS@GBT_TEST $d:\git\resus\db\src\resus\packages\ABG_MEMTOOLS-body.SQL
1/1 ERROR Db Object has changed. Resolve any merge failure and compile again.
```
When I use "Run current File AS Script" I always see this in the terminal window - even if the code is erroneous:
```
> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\node_modules\gulp\bin\gulp.js --cwd d:\git\resus\db --gulpfile c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\out\gulpfile.js --color true --silent true run --env GBT_TEST --file d:\git\resus\db\src\resus\packages\ABG_MEMTOOLS-body.SQL <

Success => RESUS@GBT_TEST $d:\git\resus\db\src\resus\packages\ABG_MEMTOOLS-body.SQL
=============================== STDOUT ===============================
Session ge�ndert.

Vordefinieren von Variablen

Session ge�ndert.

Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.
```

When the compilation throws errors, I don't see it neither in terminal window nor in problems windows.

I'm using current version
```
[0.3.13] - 2019-10-25
Add problem matcher for scripts and SQLcl as a default CLI #28
```

This is oradewrc.json:
``` json
{
	"package.input": [
		"./src/**/packages/*.SQL",
		"./src/**/trigger/*.SQL",
		"./src/**/views/*.SQL"
	],
	"package.exclude": ["./scripts/**/+(file|run)*.SQL"],
	"package.output": "./deploy/Run.sql",
	"package.encoding": "windows-1252",
	"package.templating": false,
	"source.input": ["./src/**/*.SQL"],
	"source.encoding": "windows-1252",
    "source.pattern": {
        "packageSpec": "./src/{schema-name}/packages/{object-name}-spec.SQL",
        "packageBody": "./src/{schema-name}/packages/{object-name}-body.SQL",
        "trigger": "./src/{schema-name}/trigger/{object-name}-trigger.SQL",
        "views": "./src/{schema-name}/views/{object-name}-view.SQL"
      },
	"compile.warnings": "NONE",
	"compile.force": false,
	"compile.stageFile": true,
	"import.getDdlFunction": "dbms_metadata.get_ddl"
}
```

What am I doing wrong?

**Comment by mickeypearce** [comment]
Try changing "compile.force" to "true" - if you are compiling with "Compile current file". It would ignore "object changed on db" error.

**Comment by true-hb** [comment]
I don't use SQL Developer.

In SQL*Plus I get the following:
```
SQL> @D:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL

Warning: Package created with compilation errors.

SQL> sho err
Errors for PACKAGE ABG_MEMTOOLS:

LINE/COL ERROR
-------- -----------------------------------------------------------------
27/17    PL/SQL: Declaration ignored
27/28    PLS-00201: identifier 'TRUEX' must be declared
```

**Comment by true-hb** [comment]
I changed `"compile.force": true`

Now I always get
`494/17 ERROR PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:   ;The symbol ";" was substituted for "end-of-file" to continue.`

This does not depend on ending with `END ;` or ending with 
`/
`

**Comment by mickeypearce** [comment]
Ok, fair enough.
Compiling just this package, just one statement, without grants at the end, should work with "Compile current file".

**Comment by true-hb** [comment]
Ok,

File starts with 
`CREATE OR REPLACE PACKAGE ABG_MEMTOOLS AS`
and ends with 
`END ABG_MEMTOOLS ;`

with "Compile Current File" the terminal windows shows ```

> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\node_modules\gulp\bin\gulp.js --cwd d:\git\resus\db --gulpfile c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\out\gulpfile.js --color true --silent true compile --env GBT_TEST --file d:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL <

Failure => RESUS@GBT_TEST $d:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL
494/17 ERROR PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:   ;The symbol ";" was substituted for "end-of-file" to continue.

Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.
```
and when I copy the content in the problem window I get this:
```
{
	"resource": "/d:/git/resus/db/src/RESUS/packages/ABG_MEMTOOLS-spec.SQL",
	"owner": "external",
	"severity": 8,
	"message": "PLS-00103: Encountered the symbol \"end-of-file\" when expecting one of the following:   ;The symbol \";\" was substituted for \"end-of-file\" to continue.",
	"startLineNumber": 494,
	"startColumn": 17,
	"endLineNumber": 494,
	"endColumn": 17
}
```
Any idea?

**Comment by mickeypearce** [comment]
What code is at line 494/17, is this the end of package or something else?

**Comment by mickeypearce** [comment]
I tried `oradew.json` from your example and it worked (apart from having your PL/SQL source code to test compilation). 

The only problem I found is that:
"views" is a non existent property use "view" instead...
```
"source.pattern": {
  "packageSpec": "./src/{schema-name}/packages/{object-name}-spec.SQL",
  "packageBody": "./src/{schema-name}/packages/{object-name}-body.SQL",
  "trigger": "./src/{schema-name}/trigger/{object-name}-trigger.SQL",
  "view": "./src/{schema-name}/views/{object-name}-view.SQL"
}
```

**Comment by true-hb** [comment]
Thank you for your corrections on my oracdewrc.json ;-)

I found the reason why "Compile Current File" throws `ERROR PLS-00103`.

This works: `END ABG_MEMTOOLS;`
And this works too: `END  ;`
Even this works: 
```
END ABG_MEMTOOLS;
/

```
But this throws the error: `END ABG_MEMTOOLS ;`
The problem seems to be the space character before semicolon.
When I use "Run Current File As Script" instead, no error is thrown with the space before the semicolon and a valid object is created in the database.

The problem with "Run Current File As Script" is still that just no error is thrown, if there is an error.
The object in database is created, but (of course) it is invalid.

**Comment by mickeypearce** [comment]
If you execute with "Run Current File As Script" you should add "/" at the end and use "sql" not "sqlplus".
"sqlplus" throws only "Warning: Package created with compilation errors.", but "sql" (SQLcl) has proper error-with-line reporting.

**Comment by mickeypearce** [comment]
Can you please try a file with simple erroneous block:
```
begin
  
end;
/
```
That should definitely throw somehing. 🙏

**Comment by mickeypearce** [comment]
Which version of SQLcl do you use?

This executes in the background in command line: `exit | "${cli}" -S ${connString} @"${filename}"`
In your case : `exit | "C:\\oracle\\product\\sqlcl\\bin\\sql.exe" -S username/password@tnsAlias @"d:\git\resus\db\src\RESUS\sqlplus\testmp.SQL"`

**Comment by true-hb** [comment]
Version is `SQLcl: Release 19.2.1 Production auf Di. Okt. 29 08:54:35 2019`

```
D:\git\resus\db>exit | "C:\\oracle\\product\\sqlcl\\bin\\sql.exe" -S resus/****@res_test @"d:\git\resus\db\src\RESUS\sqlplus\testmp.SQL"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by oracle.dbtools.raptor.utils.WindowsUtility (file:/C:/oracle/product/sqlcl/lib/dbtools-common.jar) to method java.util.prefs.WindowsPreferences.WindowsRegOpenKey(int,byte[],int)   
WARNING: Please consider reporting this to the maintainers of oracle.dbtools.raptor.utils.WindowsUtility
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

When I start sqlcl without parameters I get the same message. When I start any SQL-Command, (e.g. `select sysdate from dual;`) I get this message:
```
java.io.UnsupportedEncodingException: WE8MSWIN1252
        at java.base/java.lang.StringCoding.encode(Unknown Source)
        at java.base/java.lang.String.getBytes(Unknown Source)
        at oracle.dbtools.db.ResultSetFormatter.write(ResultSetFormatter.java:710)
        at oracle.dbtools.db.ResultSetFormatter.write(ResultSetFormatter.java:703)
        at oracle.dbtools.db.SQLPLUSCmdFormatter.rset2sqlplus(SQLPLUSCmdFormatter.java:2278)
        at oracle.dbtools.db.ResultSetFormatter.rset2sqlplus(ResultSetFormatter.java:334)
        at oracle.dbtools.db.ResultSetFormatter.rset2sqlplus(ResultSetFormatter.java:308)
        at oracle.dbtools.db.ResultSetFormatter.formatResults(ResultSetFormatter.java:153)
        at oracle.dbtools.db.ResultSetFormatter.formatResults(ResultSetFormatter.java:71)
        at oracle.dbtools.raptor.newscriptrunner.SQL.processResultSet(SQL.java:798)
        at oracle.dbtools.raptor.newscriptrunner.SQL.executeQuery(SQL.java:709)
        at oracle.dbtools.raptor.newscriptrunner.SQL.run(SQL.java:83)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.runSQL(ScriptRunner.java:405)
        at oracle.dbtools.raptor.newscriptrunner.ScriptRunner.run(ScriptRunner.java:231)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:344)
        at oracle.dbtools.raptor.newscriptrunner.ScriptExecutor.run(ScriptExecutor.java:227)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.process(SqlCli.java:405)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.processLine(SqlCli.java:416)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.startSQLPlus(SqlCli.java:1250)
        at oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli.main(SqlCli.java:492)
```
I can get around this mistake by `set encoding ibm852`. Unfortunately I can't remember, where I found this hint.

I will look for a way to fix it. Do you perhaps have an idea?

**Comment by mickeypearce** [comment]
I use DB with `EE8MSWIN1250` encoding and compile `win1250` encoded files.

**Comment by true-hb** [comment]
sqlcl only works with `set encoding 852`. I don't understand why. I also haven't figured out how to initialize it. Google doesn't help me either.  I am desperate and frustrated. I dedicate myself to other topics.

**Comment by true-hb** [comment]
I tried to run sqlcl under windows subsystem for linux (bash), It works without problems. cmd.exe and powershell both make problems.
Do you have an idea how I can say oradew-plugin to use this?
Or do you see a possibility to tell sqlcl always to use `encoding 852` for our use case?

**Comment by mickeypearce** [comment]
In VScode there is a command: "Terminal: Select Default Shell".

**Comment by true-hb** [comment]
Ok. I have set `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe"` and `"oradew.cliExecutable": "/mnt/c/oracle/product/sqlcl/bin/sql"`.
When I "Run Current File As A Script" I get this:
```
> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\node_modules\gulp\bin\gulp.js --cwd d:\git\resus\db --gulpfile c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\out\gulpfile.js --color true --silent true run --env GBT_TEST --file d:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL <

Command failed: exit | "/mnt/c/oracle/product/sqlcl/bin/sql" -S resus/resusdba@gbt_test @"ABG_MEMTOOLS-spec.SQL"
Das System kann den angegebenen Pfad nicht finden.


Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.
```
When I open a the built-in terminal and run `/mnt/c/oracle/product/sqlcl/bin/sql resus@172.16.255.119:1521/ORACLEDB` it works without problems.

**Comment by mickeypearce** [comment]
Sorry, I misunderstood you there. I thought you were talking about a bash shell on Windows, not a shell inside WSL.

I think there is a difference in default codepage 
 on your Windows system vs WSL system (Linux)...

**Comment by rygo18** [comment]
@mickeypearce This was also broken for me when I upgraded to 0.3.13. I don't have SQLcl installed, only SQLPlus, so was getting a "could not find 'sql'" type of error.
Changing the default to "sqlplus" in oradew.cliExecutable in the package.json fixed the issue for me.
I imagine more people will run in to this issue who don't have SQLcl installed.

**Comment by true-hb** [comment]
with sqlplus the compilation works and a warning is shown in the terminal window:
```
> Executing task: C:\Program Files\nodejs\node.exe c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\node_modules\gulp\bin\gulp.js --cwd d:\git\resus\db --gulpfile c:\Users\Truetken-H\.vscode\extensions\mp.oradew-vscode-0.3.13\out\gulpfile.js --color true --silent true run --env GBT_TEST --file d:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL <

Success => RESUS@GBT_TEST $d:\git\resus\db\src\RESUS\packages\ABG_MEMTOOLS-spec.SQL
=============================== STDOUT ===============================
Warning: Package created with compilation errors.

Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.
```
But I don't see any message in problems window.

**Comment by rygo18** [comment]
@true-hb You probably need to include "/ show errors;" at the end of your file.

**Comment by true-hb** [comment]
That's interesting: with show errors I can see the errors in the terminal window and in the problem window.
It even works when the script ends with a GRANT statement:
```
....
END ABG_MEMTOOLS;
/
GRANT execute ON ABG_MEMTOOLS to public
/
show errors
```
@mickeypearce : can you perhaps integrate the `show errors` in your plugin?

Then I woud be lucky :-)

**Comment by mickeypearce** [comment]
Thanks, @rygo18 .

I will include "show errors" in the case of "sqlplus" as it used to be:
  https://github.com/mickeypearce/oradew-vscode/blob/35bc600998232225e860917f65b81091e4d83967/src/common/base.js#L225

**Comment by mickeypearce** [comment]
@true-hb , @true-hb: `SQLcl` is now part of Oracle Client, which client version do you use?

**Comment by true-hb** [comment]
I have just downloaded and unpacked the zip-file from https://www.oracle.com/tools/downloads/sqlcl-downloads.html
The installed Oracle Client (as a standard in out IT department) is instantclient 10.2. sqlcl is not part of this installation.

**Comment by rygo18** [comment]
Thanks @mickeypearce, a valid suggestion :). I don't use SQLcl at all. Just SQL Developer and SQL*Plus.
I'd only say that the change in 0.3.13 is going to break the extension for anyone who doesn't have SQLcl installed, unless they update their settings I presume? Personally, I think the safer transition to SQLcl for people would be that SQL*Plus remains the default and users can update the settings so that SQLcl is the client if they choose.

**Comment by mickeypearce** [comment]
I suggested SQLcl because it has a line offset in errors, so for example running a script with multiple DML or DDL statements:
```
INSERT INTO...
INSERT INTO...
BEGIN
END;
/
```
, will correctly match problems. SQLPlus won't, as it doesn't output the block offset.

SQLcl is also part of SQL Developer (..../sqldeveloper/bin/sql), so it should be relatively easy migrate to from SQLPlus.

But I totaly understand your concern as for majority sqlplus will work out of the box I guess.

**Comment by true-hb** [comment]
I have found found a way to use sqlcl on my installation.
I created a sql.bat in which I explicitly set the environment variable NLS_LANG
```
set NLS_LANG=AMERICAN_AMERICA.cp1252
%~dp0\sql.exe %*
```

Now Compilation works, and the errors for packages and package bodies are shown in the problems window.

**Comment by mickeypearce** [comment]
Great! Thanks a lot for sharing you solution.

**Comment by mickeypearce** [comment]
An option was added to pass environment varaibles directly to oradew process. 

In @true-hb 's case you can now set `NLS_LANG` in `settings.json`:
```json
"oradew.envVariables": {
  "NLS_LANG": ".cp1252",
}
```
...Or set ORACLE_HOME as seen here... (https://github.com/mtxr/vscode-sqltools/issues/281), etc.
